import React from 'react'

import { Box, Stack, Typography } from '@mui/material'


//Assets
import GithubIcon from '../../../assets/Contact/githubicon.png'
import LinkedinIcon from '../../../assets/Contact/linkedinicon.png'
import FigmaIcon from '../../../assets/Contact/figmaicon.png'
import DiscordIcon from '../../../assets/Contact/discordicon.png'

const SocialMedia = () => {
    return (
        <>
            <Box
                backgroundColor='#5A3392'
                maxWidth='1565px'
                height='120px'
                marginTop='35px'
                marginLeft='20px'
            >
                <Box
                    display='flex'
                >
                    <Box

                    >
                        <Stack
                            direction='column'
                        >
                            <Box
                                marginLeft='20px'
                                marginTop='5px'
                            >
                                <Typography
                                    marginTop='5px'
                                    color='#FFFFFF'
                                    display='flex'
                                    letterSpacing='5px'
                                >
                                    <Box
                                        marginRight='10px'
                                    >
                                        <img
                                            alt='github'
                                            src={GithubIcon}
                                            width='25px'
                                        />
                                    </Box>
                                    <Typography
                                        marginRight='10px'
                                        letterSpacing='5px'
                                    >
                                        GitHub:
                                    </Typography>
                                    <a 
                                    href='https://github.com/wakenedo'
                                    style={{
                                        textDecoration:'none',
                                        color:'#FFFFFF'
                                    }}
                                    >
                                        @wakenedo
                                    </a>
                                </Typography>
                                <Typography
                                    marginTop='5px'
                                    color='#FFFFFF'
                                    display='flex'
                                    letterSpacing='5px'
                                >
                                    <Box
                                        marginRight='10px'
                                    >
                                        <img
                                            alt='github'
                                            src={LinkedinIcon}
                                            width='25px'
                                        />
                                    </Box>
                                    <Typography
                                        marginRight='10px'
                                        letterSpacing='5px'
                                    >
                                        LinkedIn:
                                    </Typography>
                                    <a 
                                    href='https://www.linkedin.com/in/alexandre-alvarenga-developer/'
                                    style={{
                                        textDecoration:'none',
                                        color:'#FFFFFF'
                                    }}
                                    >
                                        @alexandre-alvarenga-developer
                                    </a>
                                </Typography>
                                <Typography
                                    marginTop='5px'
                                    color='#FFFFFF'
                                    display='flex'
                                    letterSpacing='5px'
                                >
                                    <Box
                                        marginRight='10px'
                                    >
                                        <img
                                            alt='github'
                                            src={FigmaIcon}
                                            width='25px'
                                        />
                                    </Box>
                                    <Typography
                                        marginRight='10px'
                                        letterSpacing='5px'
                                    >
                                        Figma:
                                    </Typography>
                                    <a 
                                    href='https://www.figma.com/?fuid='
                                    style={{
                                        textDecoration:'none',
                                        color:'#FFFFFF'
                                    }}
                                    >
                                        @wakenedo
                                    </a>
                                </Typography>
                            </Box>
                        </Stack>
                    </Box>
                    <Box
                        marginLeft='250px'
                    >
                        <Stack
                            direction='column'
                        >
                            <Box
                                marginLeft='20px'
                                marginTop='5px'
                            >
                                <Typography
                                    marginTop='5px'
                                    color='#FFFFFF'
                                    display='flex'
                                    letterSpacing='5px'
                                >
                                    <Box
                                        marginRight='10px'
                                    >
                                        <img
                                            alt='github'
                                            src={DiscordIcon}
                                            width='25px'
                                        />
                                    </Box>
                                    <Typography
                                        marginRight='10px'
                                        letterSpacing='5px'
                                    >
                                        Discord:
                                    </Typography>
                                    <a 
                                    href='https://discord.com/'
                                    style={{
                                        textDecoration:'none',
                                        color:'#FFFFFF'
                                    }}
                                    >
                                        @wakenedo
                                    </a>
                                </Typography>
                            </Box>
                        </Stack>
                    </Box>
                </Box>
            </Box>
        </>
    )
}

export default SocialMedia